# Generated by Django 4.1.3 on 2022-11-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prediccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temp", models.IntegerField(default=1)),
                ("conduc", models.IntegerField(default=1)),
                ("difer", models.IntegerField(default=1)),
                ("flujoA", models.IntegerField(default=1)),
            ],
        ),
    ]
