# Generated by Django 4.1.3 on 2022-12-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_prediccion_temp"),
    ]

    operations = [
        migrations.AddField(
            model_name="prediccion",
            name="user",
            field=models.TextField(default="none"),
        ),
    ]
